version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.8.0
    container_name: elasticsearch
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    ports:
      - 9200:9200
      - 9300:9300

  api2:
    build:
      context: api2/  #Dockerfile path
      dockerfile: Dockerfile  #Dockerfile name
    container_name: api2
    depends_on:
      - elasticsearch
    command: python api2/api2/manage.py runserver 0.0.0.0:8002
    volumes:
      - .:/django
    ports:
      - 8002:8002
    restart: always
    tty: true
    links:
      - elasticsearch

  api1:
    build:
      context: api1/
      dockerfile: Dockerfile
    container_name: api1
    ports:
      - 8001:8001
    depends_on:
      - api2
    links:
      - api2
    command: go run main.go




