version: '3'
services:
  web:
    build:
      context: .  #Dockerfile path
      dockerfile: Dockerfile  #Dockerfile name
    command: python api2/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/django
    ports:
      - "8000:8000"