version: "3.2"

services: 
    app:
        image: amd64/golang:1.14
        build: 
            context: .
            dockerfile: Dockerfile
        command: ls
        ports:
            - 8080:8080
        volumes:
            - .:/app